import json
import pandas as pd
import numpy as np
from openai import OpenAI

client = OpenAI()

INPUT_FILE = "synthetic_data.jsonl"      # same file generated by Step 1
OUTPUT_FILE = "safety_embeddings.pkl"    # will contain: text, label, embedding


def load_dataset():
    """
    Loads JSONL file into a pandas DataFrame.
    """
    records = []
    with open(INPUT_FILE, "r") as f:
        for line in f:
            item = json.loads(line.strip())
            records.append(item)
    return pd.DataFrame(records)


def create_embedding(text):
    """
    Generates a vector embedding for a single text.
    """
    response = client.embeddings.create(
        model="text-embedding-3-large",
        input=text
    )
    return response.data[0].embedding


def main():
    df = load_dataset()
    print(f"📄 Loaded {len(df)} samples from {INPUT_FILE}")

    embeddings = []
    for i, text in enumerate(df["text"]):
        emb = create_embedding(text)
        embeddings.append(emb)
        print(f"🔹 Embedded {i+1}/{len(df)}")

    df["embedding"] = embeddings

    df.to_pickle(OUTPUT_FILE)
    print(f"\n✅ Saved embeddings → {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
